---
- name: ensure monit is installed
  apt: pkg=monit state=installed



- name: Monit | Update the monit configuration (/etc/monit/monitrc)
  template:
    src: "monitrc.j2"
    dest: "/etc/monit/monitrc"
  notify:
    - restart monit
